# Generated by Django 4.0.4 on 2022-05-22 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id_split_score', models.IntegerField(primary_key=True, serialize=False)),
                ('split_score', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id_user_score', models.IntegerField(primary_key=True, serialize=False)),
                ('user_score', models.CharField(max_length=255)),
                ('id_collectable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.collectable')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.matchscore')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id_rating', models.IntegerField(primary_key=True, serialize=False)),
                ('puzle', models.CharField(max_length=255)),
                ('collectable', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('misions', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matchscore',
            name='id_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.rating'),
        ),
    ]
