# Generated by Django 4.0.4 on 2022-05-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
